CREATE TABLE companies (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,

    name VARCHAR(160) NOT NULL UNIQUE,

    description TEXT NULL,

    is_active TINYINT(1) NOT NULL DEFAULT 1,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
